FROM alpine:3.21

WORKDIR /app

# Instalar dependências
RUN apk add --no-cache \
    gcc \
    musl-dev \
    zeromq-dev \
    msgpack-c-dev

# Copiar código
COPY ../cliente.c .

# Compilar com flags corretas
RUN gcc -o cliente cliente.c -lzmq -lmsgpackc -I/usr/include -L/usr/lib

CMD ["./cliente"]
