FROM alpine:3.21

WORKDIR /app

# Instalar dependências de compilação e runtime
RUN apk add --no-cache \
    gcc \
    musl-dev \
    make \
    zeromq-dev \
    msgpack-c-dev

# Copiar código fonte
COPY ../cliente.c .
COPY ../Makefile .

# Compilar
RUN make cliente

CMD ["./cliente"]

